### ISSUE TITLE
Ask to Resume last position on movie start

### ISSUE THREAD

**Issue by nagysifa** [mx3L/subssupport#2]
What version of the product are you using? On what operating system?
- mp2 v0.60 + subssupport v1.5.3
- OpenPLi 4 (kernel 3.1.1) and PBnigma 5.0.0 (kernel 3.1.1) on VU+ UNO

Changing the option "Resume last position on movie start" from "Resume" to "Ask" does not change the player behavior. It always resumes ( without asking ) the movie to its last played position.

Does this problem affect anyone else ?
![resume](https://cloud.githubusercontent.com/assets/14113441/9665617/bcb13200-5271-11e5-8249-b9dd67128c8a.jpg)

Kind regards : Zoltan.

**Comment by mx3L** [comment]
Yes, it's not working like you're saying. I already fixed it:
https://github.com/mx3L/mediaplayer2/commit/69f8ff36dbe89aecb777a903218dfd6ab489fc10

You can test it for yourself, you just need to clone mediaplayer2 repository and run create_ipk.sh script, if you are on linux, or just copy over mp2 files in receiver.

I will add new version later, since I want to make some adjustments.

**Comment by nagysifa** [comment]
Great, I'll settle for the new version when it arrives!
